Promo:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/promosi"
      title: "Semua Promo"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-shabu-jin"
      title: "Promo Shabu Jin"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-magal-korean-bbq"
      title: "Promo Magal"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-jin-ramen"
      title: "Promo Jin Ramen"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-form-the-sea"
      title: "Promo From the Sea"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-8treasures"
      title: "Promo 8 Treasures"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-8treasures-noodle-house"
      title: "Promo 8 Treasures Noodle House"
    - url: "https://www.banksinarmas.com/id/promosi/snk-gionsushi"
      title: "Promo Gion Sushi"
    - url: "https://www.banksinarmas.com/id/promosi/snk-nob"
      title: "Promo NOB Cafée & Patisserie"
    - url: "https://www.banksinarmas.com/id/promosi/snk-weenamkee"
      title: "Promo Wee Nam Kee"
    - url: "https://www.banksinarmas.com/id/promosi/brastagi-supermarket"
      title: "Promo Supermarket Brastagi"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-putien-restaurant"
      title: "Promo Putien"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-xxi"
      title: "Promo XXI Bioskop"
    - url: "https://www.banksinarmas.com/id/promosi/gojek-saturday-visa"
      title: "Promo Gojek"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-may-star-restaurant"
      title: "Promo May Star"
    - url: "https://www.banksinarmas.com/id/promosi/kk-bicester-collection"
      title: "Promo Bicester Collection"
    - url: "https://www.banksinarmas.com/id/promosi/kk-marhen-j"
      title: "Promo Marhen J"
    - url: "https://www.banksinarmas.com/id/promosi/kk-qris-mcd"
      title: "Promo QRIS McDonald's"
    - url: "https://www.banksinarmas.com/id/promosi/kk-pizza-hut"
      title: "Promo Pizza Hut"
    - url: "https://www.banksinarmas.com/id/promosi/kk-grand-mansion"
      title: "Promo Grand Mansion"
    - url: "https://www.banksinarmas.com/id/promosi/kk-sushi-manna"
      title: "Promo Sushi Manna"
    - url: "https://www.banksinarmas.com/id/promosi/buka-deposito-online"
      title: "Promo Buka Deposito Online"
    - url: "https://www.banksinarmas.com/id/promosi/buka-tabungan-simpel"
      title: "Promo Buka Tabungan Simpel"
    - url: "https://www.banksinarmas.com/id/promosi/pijat-chien-khang-thang-thai-reflexology"
      title: "Promo Chien Khang Thang Pijat Thai Reflexology"
    - url: "https://www.banksinarmas.com/id/promosi/jumpstart-ngopi-hemat"
      title: "Promo QRIS Jumpstart Ngopi Hemat"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-angke-restaurant"
      title: "Promo Angke"

Produk:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/simpanan"
      title: "Produk Simpanan"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit"
      title: "Produk Kartu Kredit"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana"
      title: "Produk Reksadana"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance"
      title: "Produk Bancasurance"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman"
      title: "Produk Pinjaman"

Kartu Kredit:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-indigo"
      title: "Kartu Kredit Personal 'Silver Indigo'"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-alfamart"
      title: "Kartu Kredit Personal 'Silver Alfamart'"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-personal"
      title: "Kartu Kredit Personal 'Platinum'"
    - url: "https://www.banksinarmas.com/id/bisnis/produk/pinjaman/kartu-kredit-korporat"
      title: "Kartu Kredit Korporat 'Platinum'"

Reksadana:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-rupiah-plus"
      title: "Reksadana Danamas Rupiah Plus"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-pasti"
      title: "Reksadana Danamas Pasti"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-stabil"
      title: "Reksadana Danamas Stabil"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-dollar"
      title: "Reksadana Danamas Dollar"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-dollar"
      title: "Reksadana Simas Satu"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/simas-satu-prima"
      title: "Reksadana Simas Satu Prima"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/simas-syariah-berkembang"
      title: "Reksadana Simas Syariah Berkembang"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/danamas-saham"
      title: "Reksadana Danamas Saham"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/simas-saham-unggulan"
      title: "Reksadana Simas Saham Unggulan"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/simas-saham-maksima"
      title: "Reksadana Simas Saham Maksima"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/reksadana-sip"
      title: "Reksadana Simas Investment Plan"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/star-stable-income-fund"
      title: "Reksadana STAR Stable Income Fund"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/simas-pendapatan-optima"
      title: "Reksadana Simas Pendapatan Optima"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana/indeks-simas-sri-kehati"
      title: "Reksadana Indeks Simas SRI-Kehati"

Bancassurance:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/simas-income-protection"
      title: "Bancassurance Simas Income Protection"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/sinarmas-pension-plan"
      title: "Bancassurance Sinarmas Pension Plan"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/sinarmas-optima-plus"
      title: "Bancassurance Sinarmas Optima Plus"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/smile-flexi-link"
      title: "Bancassurance Smile Flexi Link"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/sinarmas-maxi-life"
      title: "Bancassurance Sinarmas Maxi Life"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/asuransi-simas-kid"
      title: "Bancassurance Simas KID"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/siji-fixed-link"
      title: "Bancassurance SiJi Fixed Link"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/simas-prima"
      title: "Bancassurance Simas Prima"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/dana-sejahtera"
      title: "Bancassurance Dana Sejahtera"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/smile-medical"
      title: "Bancassurance Smile Medical"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/smile-hospital-plus"
      title: "Bancassurance Smile Hospital Plus"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/smart-investa-link"
      title: "Bancassurance Smart Investa Link"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/star-premium-dollar"
      title: "Bancassurance Star Premium Dollar"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance/asuransi-ku"
      title: "Bancassurance AsuransiKu"

Pinjaman:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/kredit-pemilikan-rumah"
      title: "Pinjaman Kredit Pemilikan Rumah (KPR)"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/kredit-tanpa-agunan-payroll"
      title: "Pinjaman Kredit Tanpa Agunan Payroll"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/kta-tki"
      title: "Pinjaman KUR Tenaga Kerja Indonesia"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/Kredit-Mikro"
      title: "Pinjaman Kredit Mikro"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/supply-chain-financing"
      title: "Pinjaman Supply Chain Financing"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/kmu-petani-sawit"
      title: "Pinjaman KMU Petani Sawit"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/kta-simas-agri"
      title: "Pinjaman KTA Simas Agri"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/perluasan-agunan"
      title: "Pinjaman Perluasan Agunan"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman/simas-dana-tunai"
      title: "Pinjaman Simas Dana Tunai"

Kurs Mata Uang:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/kurs"
      title: "Info Kurs"

Profil Bank Sinarmas:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/profil-bank-sinarmas"
      title: "Profil Bank Sinarmas"

Manajemen Bank Sinarmas:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/managemen-bank-sinarmas"
      title: "Manajemen Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/tjendrawati-Widjaja"
      title: "Profil Tjendrawati Widjaja Presiden Komisaris Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/sammy-kristamuljana"
      title: "Profil Sammy Kristamuljana Komisaris Independen Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/rusmin"
      title: "Profil Rusmin Komisaris Independen Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/frenky-tirtowijoyo"
      title: "Profil Frenky Tirtowijoyo Direktur Utama Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/miko-andidjaja"
      title: "Profil Miko Andidjaja Direktur Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/ekajaya-ongny-putra"
      title: "Profil Ekajaya Ongny Putra Direktur Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/enny-kamal"
      title: "Profil Enny Kamal Direktur Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/sendy"
      title: "Profil Sendy Direktur Bank Sinarmas"
    
    
